### ISSUE TITLE
Initialization of constants in Fluidity_Chem_Mods.py 

### ISSUE THREAD

**Issue by bangerth** [paddywball/BDD21#2]
The file `Fluidity_Chem_Mods.py` uses an interesting scheme to initialize variables: It first initializes *local* variables in the constructor, and then assigns these values to the member variables of the class. That makes it difficult to see whether all members are initialized, and what their values are. Why not do it in one step?

**Comment by paddywball** [comment]
Hi Wolfgang,

I do that because there are 'standard' variables which are the most common, but then for some runs you want to use different ones. In this example I am updating the code to have a certain amount of water in the source, rather than being anhydrous.

I hope that makes sense. Any reply might be slow as I'm heading up Mnt Yale tomorrow!

Cheers,

Paddy

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Wolfgang Bangerth ***@***.***>
Sent: Tuesday, 15 June 2021, 15:43
To: paddywball/BDD21
Cc: Subscribed
Subject: [paddywball/BDD21] Initialization of constants in Fluidity_Chem_Mods.py (#2)


The file Fluidity_Chem_Mods.py uses an interesting scheme to initialize variables: It first initializes local variables in the constructor, and then assigns these values to the member variables of the class. That makes it difficult to see whether all members are initialized, and what their values are. Why not do it in one step?

**Comment by bangerth** [comment]
What I mean (and maybe I misunderstand what you are trying to do) is this: Whether you write
```
  A = 42
  self.A = A
```
or
```
  self.A = 42
```
is the same. The latter just happens to be easier to read :-)

Good luck on Yale -- it's a fun climb, take the last quarter mile on the nose of the ridge instead of the easier bypass on the right! :-)

**Comment by paddywball** [comment]
Ah I see, 

Yes, your suggestion is sensible and I will make that change.

**Comment by marcfehling** [comment]
> It first initializes local variables in the constructor, and then assigns these values to the member variables of the class.

Paddy does not initialize local variables per se, but sets default values for constructor parameters and then assigns them to member variables. This way he can construct new objects of this class that slightly vary from the default case via constructor parameters, e.g., `my_chem = Fluidity_Chem(gamma=0.8)`.

For the amount of parameters you have, this looks very tedious to me. I would directly set the default values in the constructor as @bangerth suggested. If you need values  that differ from the default, you can simply change them like this
```
my_chem = Fluidity_Chem()
my_chem.gamma=0.8
```

Note: I think this is the right syntax. I haven't used `python` in a while...

**Comment by paddywball** [comment]
Having looked into this properly, I think you always have to write it twice?
Once in the brackets at the beginning of the function and then once within the function itself?

At the moment I am writing
def __init__(self, A=42., B=43): 
    self.A = A
    self.B =B

I could change this to
def __init__(self,A,B):
    self.A=42.
    self.B=43.

as Wolfgang suggests but I don't see how this change makes it any easier to read personally, you still have to write everything twice...

**Comment by marcfehling** [comment]
Leave the constructor parameters altogether and write it like:
```
class Foo:
  def __init__(self):
    self.A = 42.
    self.B = 43.
```

If you want to change the values, you can write
```
f = Foo()
f.A = 13
```
